FROM wordpress

ARG ENVIRONMENT
ARG WORDPRESS_DB_NAME
ARG WORDPRESS_DB_PASSWORD
ARG WORDPRESS_DB_USER
ARG WORDPRESS_DB_HOST
ARG WORDPRESS_ADMIN_USER
ARG WORDPRESS_ADMIN_PASSWORD
ARG WORDPRESS_ADMIN_EMAIL
ARG WORDPRESS_DESCRIPTION
ARG WORDPRESS_TITLE
ARG WORDPRESS_URL
ARG S3_UPLOADS_BUCKET
ARG S3_UPLOADS_KEY
ARG S3_UPLOADS_SECRET
ARG S3_UPLOADS_REGION
ARG S3_UPLOADS_USE_LOCAL
ENV ENVIRONMENT=$ENVIRONMENT
ENV WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
ENV WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
ENV WORDPRESS_DB_USER=$WORDPRESS_DB_USER
ENV WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
ENV WORDPRESS_ADMIN_USER=$WORDPRESS_ADMIN_USER
ENV WORDPRESS_ADMIN_PASSWORD=$WORDPRESS_ADMIN_PASSWORD
ENV WORDPRESS_ADMIN_EMAIL=$WORDPRESS_ADMIN_EMAIL
ENV WORDPRESS_DESCRIPTION=$WORDPRESS_DESCRIPTION
ENV WORDPRESS_TITLE=$WORDPRESS_TITLE
ENV WORDPRESS_URL=$WORDPRESS_URL
ENV S3_UPLOADS_BUCKET=$S3_UPLOADS_BUCKET
ENV S3_UPLOADS_KEY=$S3_UPLOADS_KEY
ENV S3_UPLOADS_SECRET=$S3_UPLOADS_SECRET
ENV S3_UPLOADS_REGION=$S3_UPLOADS_REGION
ENV S3_UPLOADS_USE_LOCAL=$S3_UPLOADS_USE_LOCAL


WORKDIR /var/www/html
COPY . /var/www/html
COPY /themes/swace-digital /var/www/html/wp-content/themes/swace-digital
RUN mv "$PHP_INI_DIR"/php.ini-development "$PHP_INI_DIR"/php.ini

# install_wordpress.sh & misc. dependencies
RUN apt-get update; \
  apt-get install -yq mariadb-client netcat sudo less git unzip wget nano

# Increase Wordpress Upload Limit
RUN touch /usr/local/etc/php/conf.d/uploads.ini \
  && echo "upload_max_filesize = 64M;" >> /usr/local/etc/php/conf.d/uploads.ini \
  && echo "post_max_size = 128M;" >> /usr/local/etc/php/conf.d/uploads.ini

# wp-cli
RUN curl -sL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o wp; \
  chmod +x wp; \
  mv wp /usr/local/bin/; \
  mkdir /var/www/.wp-cli;

# composer
RUN curl -sL https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer | php; \
  mv composer.phar /usr/local/bin/composer; \
  mkdir /var/www/.composer; \
  chown www-data:www-data /var/www/.composer

# include composer-installed executables in $PATH
ENV PATH="/var/www/.composer/vendor/bin:${PATH}"

COPY docker/SWACE_PLACEHOLDER.png /var/tmp/SWACE_PLACEHOLDER.png
COPY docker/wp-cli.yml /var/www/html/wp-cli.yml

EXPOSE 80



COPY docker/install_wordpress.sh /usr/local/bin/install_wordpress
RUN chmod +x /usr/local/bin/install_wordpress
COPY docker/docker_start.sh /usr/local/bin/docker_start
RUN chmod +x /usr/local/bin/docker_start

CMD docker_start